security:
    providers:
        all:
            chain:
                providers: [static, dynamic]
        static:
            memory:
                users:
                   super: { password: x, roles: [ 'ROLE_SUPER' ] }
                   admin: { password: x, roles: [ 'ROLE_ADMIN' ] }
                   user:  { password: x, roles: [ 'ROLE_USER' ] }
        dynamic:
            entity: { class: ExampleApplicationBundle:User }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        Example\ApplicationBundle\Entity\User: sha512

    firewalls:
        user:
            provider: dynamic
            pattern: ^/
            anonymous: ~
            form_login:
                check_path: /security/check
                login_path: /security/login
                username_parameter: "form[username]"
                password_parameter: "form[password]"
                use_forward: false
            logout:
                path: /security/logout
                target: /
            http_basic:
                provider: all
                realm: "Secured Application Area"
            switch_user: { role: ROLE_SWITCH, parameter: _switch }
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~
                remember_me_parameter: "form[remember]"
        development:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    acl:
        connection: default

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER: [ROLE_USER, ROLE_ADMIN, ROLE_SWITCH]

    access_control:
        - { path: ^/administration/group, role: ROLE_USER }
        - { path: ^/administration/user, role: ROLE_USER }
        - { path: ^/administration, role: ROLE_USER }
        - { path: ^/application, role: ROLE_USER }
        - { path: ^/security/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY}

jms_security_extra:
    secure_all_services:  false
    expressions:          true